print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
print('What do dentists call an astronuat\'s cavity?')
input()
print('A black hole!')
print()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interrupting cow uh', end='')
print('-MOO!')